version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - static:/web/static:ro
    depends_on:
      - web

  web:
    env_file: .env
    build: ./web
    expose:
      - "8000"
    command: ./entrypoint.sh
    volumes:
      - ./web:/src
      - static:/src/static
    depends_on:
      - db

volumes:
  postgres_data:
  static:
