# Generated by Django 3.0.8 on 2020-07-10 07:02

import classwork.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0004_auto_20200627_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classoffer',
            old_name='num_level',
            new_name='_num_level',
        ),
        migrations.RemoveField(
            model_name='location',
            name='map_google',
        ),
        migrations.AddField(
            model_name='classoffer',
            name='manager_approved',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='map_link',
            field=models.URLField(blank=True, verbose_name='Map Link'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='credit',
            field=models.FloatField(default=0, verbose_name='class payment credit'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='avail',
            field=models.PositiveSmallIntegerField(choices=[(0, 'On Sign-up, before week 1)'), (1, 'After week 1'), (2, 'After week 2'), (3, 'After week 3'), (4, 'After week 4'), (5, 'After week 5'), (200, 'After completion')], help_text='When is this resource available?'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='expire',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of published weeks? (0 for always)'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.URLField(blank=True, help_text='External or Internal links go here', max_length=191),
        ),
        migrations.AlterField(
            model_name='session',
            name='break_weeks',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='break weeks after this session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='flip_last_day',
            field=models.BooleanField(default=False, help_text='Possibly true if the skipped class is not on the day that normally is the end of the session.', verbose_name='due to skipped weeks, does the session ending switch between a non-key vs key day?'),
        ),
        migrations.AlterField(
            model_name='session',
            name='key_day_date',
            field=models.DateField(default=classwork.models.default_key_day, verbose_name='main class start date'),
        ),
        migrations.AlterField(
            model_name='session',
            name='max_day_shift',
            field=models.SmallIntegerField(default=-2, help_text='Use negative numbers if others are before the main class day.', verbose_name='number of days other classes are away from main class'),
        ),
        migrations.AlterField(
            model_name='session',
            name='num_weeks',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='number of class weeks'),
        ),
        migrations.AlterField(
            model_name='session',
            name='publish_date',
            field=models.DateField(blank=True, default=classwork.models.default_publish),
        ),
        migrations.AlterField(
            model_name='session',
            name='skip_weeks',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='skipped mid-session class weeks'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='full_price',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.URLField(blank=True, max_length=191),
        ),
        migrations.AlterField(
            model_name='subject',
            name='multiple_purchase_discount',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='subject',
            name='pre_pay_discount',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=9),
        ),
    ]
