# Generated by Django 2.2.8 on 2020-01-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0003_auto_20200123_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='items',
            field=models.ManyToManyField(related_name='payments', through='classwork.Registration', to='classwork.ClassOffer'),
        ),
    ]
