# Generated by Django 2.2.8 on 2020-01-28 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0004_payment_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='items',
        ),
    ]
