# Generated by Django 3.0.8 on 2020-08-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhc',
            name='uses_email_username',
            field=models.BooleanField(default=True, help_text='Typical default', verbose_name='using email as username'),
        ),
    ]
