# Generated by Django 2.2.8 on 2020-01-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190902_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhc',
            name='billing_address_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userhc',
            name='billing_address_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userhc',
            name='billing_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userhc',
            name='billing_country_code',
            field=models.CharField(blank=True, default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='userhc',
            name='billing_postcode',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
