# Generated by Django 3.0.8 on 2020-08-27 22:45

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200810_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffuser',
            options={'verbose_name': 'Staff User', 'verbose_name_plural': 'Staff Users'},
        ),
        migrations.AlterModelOptions(
            name='studentuser',
            options={'verbose_name': 'Student User', 'verbose_name_plural': 'Student Users'},
        ),
        migrations.RemoveField(
            model_name='userhc',
            name='uses_email_username',
        ),
        migrations.AddField(
            model_name='userhc',
            name='username_not_email',
            field=models.BooleanField(default=False, help_text='Leave empty to login with email (Typical use)', verbose_name='login with username, not with email'),
        ),
        migrations.AlterField(
            model_name='userhc',
            name='email',
            field=models.EmailField(blank=True, help_text='used for confirmation and typically for login', max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='userhc',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='or login name', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
