# Generated by Django 3.0.8 on 2020-07-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200224_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhc',
            name='billing_address_1',
            field=models.CharField(blank=True, max_length=191, verbose_name='Street Address (line 1)'),
        ),
        migrations.AlterField(
            model_name='userhc',
            name='billing_address_2',
            field=models.CharField(blank=True, max_length=191, verbose_name='Street Address (continued)'),
        ),
        migrations.AlterField(
            model_name='userhc',
            name='billing_city',
            field=models.CharField(blank=True, max_length=191, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='userhc',
            name='billing_country_code',
            field=models.CharField(blank=True, default='USA', max_length=191, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='userhc',
            name='billing_postcode',
            field=models.CharField(blank=True, help_text='Zip or Postal Code', max_length=191, verbose_name='Zip Code'),
        ),
    ]
