# Generated by Django 2.1.3 on 2018-12-20 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0001_initial'),
        ('users', '0002_auto_20181209_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('level', models.IntegerField(default=0, verbose_name='Student Skill Level Number')),
                ('credit', models.FloatField(default=0, verbose_name='Class Payment Credit')),
                ('taken', models.ManyToManyField(to='classwork.Subject')),
            ],
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
