# Generated by Django 3.1 on 2020-08-28 11:47

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200827_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhc',
            name='email',
            field=models.EmailField(blank=True, help_text='Used for confirmation and typically for login. ', max_length=191, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='userhc',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='userhc',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Only needed if user does not have a unique email. ', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='userhc',
            name='username_not_email',
            field=models.BooleanField(default=False, help_text='Typically left empty to use email as your login. ', verbose_name='create a username for login? '),
        ),
    ]
