# Generated by Django 3.1.4 on 2021-01-01 05:01

from django.db import migrations, models


def set_two_char_default_country(apps, schema_editor):
    Person = apps.get_model('users', 'UserHC')
    for person in Person.objects.all():
        if person.billing_country_code == 'USA':
            person.billing_country_code = 'US'
            person.save()


def set_three_char_default_country(apps, schema_editor):
    Person = apps.get_model('users', 'UserHC')
    for person in Person.objects.all():
        if person.billing_country_code == 'US':
            person.billing_country_code = 'USA'
            person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200828_0447'),
    ]

    operations = [
        migrations.RunPython(set_two_char_default_country, set_three_char_default_country),
        migrations.AlterField(
            model_name='userhc',
            name='billing_address_1',
            field=models.CharField(blank=True, max_length=95, verbose_name='street address (line 1)'),
        ),
        migrations.AlterField(
            model_name='userhc',
            name='billing_address_2',
            field=models.CharField(blank=True, max_length=95, verbose_name='street address (continued)'),
        ),
        migrations.AlterField(
            model_name='userhc',
            name='billing_city',
            field=models.CharField(blank=True, default='Seattle', max_length=95, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='userhc',
            name='billing_country_area',
            field=models.CharField(blank=True, default='WA', max_length=2, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='userhc',
            name='billing_country_code',
            field=models.CharField(blank=True, default='US', max_length=2, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='userhc',
            name='billing_postcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='zipcode'),
        ),
        migrations.AlterField(
            model_name='userhc',
            name='username_not_email',
            field=models.BooleanField(choices=[(False, 'Use email address as login. '), (True, 'Create a username. ')], default=False, help_text='Typically left empty to use email as your login. ', verbose_name='login type'),
        ),
    ]
