# Generated by Django 3.0.8 on 2020-07-25 05:35

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200717_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.userhc',),
            managers=[
                ('objects', users.models.UserManagerHC()),
            ],
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.userhc',),
            managers=[
                ('objects', users.models.UserManagerHC()),
            ],
        ),
        migrations.AlterField(
            model_name='userhc',
            name='billing_postcode',
            field=models.CharField(blank=True, help_text='Zip or Postal Code', max_length=10, verbose_name='zipcode'),
        ),
    ]
