# Generated by Django 2.1.3 on 2019-01-07 07:53

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userhc',
            managers=[
                ('objects', users.models.UserManagerHC()),
            ],
        ),
    ]
