# Generated by Django 2.1.3 on 2019-01-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0003_auto_20190116_2129'),
        ('users', '0007_auto_20190115_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='taken_classes',
            field=models.ManyToManyField(to='classwork.ClassOffer'),
        ),
    ]
