# Generated by Django 3.0.8 on 2020-07-25 06:08

import classwork.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_num_level', models.IntegerField(default=0, editable=False)),
                ('manager_approved', models.BooleanField(default=1)),
                ('class_day', models.SmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=3)),
                ('start_time', models.TimeField()),
                ('skip_weeks', models.PositiveSmallIntegerField(default=0, verbose_name='skipped mid-session class weeks')),
                ('skip_tagline', models.CharField(blank=True, max_length=46)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=191)),
                ('city', models.CharField(default='Seattle', max_length=120)),
                ('state', models.CharField(default='WA', max_length=63)),
                ('zipcode', models.CharField(max_length=15)),
                ('map_link', models.URLField(blank=True, verbose_name='Map Link')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for confirmation'), ('preauth', 'Pre-authorized'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('refunded', 'Refunded'), ('error', 'Error'), ('input', 'Input')], default='waiting', max_length=10)),
                ('fraud_status', models.CharField(choices=[('unknown', 'Unknown'), ('accept', 'Passed'), ('reject', 'Rejected'), ('review', 'Review')], default='unknown', max_length=10, verbose_name='fraud check')),
                ('fraud_message', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
                ('delivery', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
                ('tax', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
                ('description', models.TextField(blank=True, default='')),
                ('billing_first_name', models.CharField(blank=True, max_length=256)),
                ('billing_last_name', models.CharField(blank=True, max_length=256)),
                ('billing_address_1', models.CharField(blank=True, max_length=256)),
                ('billing_address_2', models.CharField(blank=True, max_length=256)),
                ('billing_city', models.CharField(blank=True, max_length=256)),
                ('billing_postcode', models.CharField(blank=True, max_length=256)),
                ('billing_country_code', models.CharField(blank=True, max_length=2)),
                ('billing_country_area', models.CharField(blank=True, max_length=256)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('customer_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('extra_data', models.TextField(blank=True, default='')),
                ('message', models.TextField(blank=True, default='')),
                ('token', models.CharField(blank=True, default='', max_length=36)),
                ('captured_amount', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
                ('full_price', models.DecimalField(decimal_places=2, default='0.0', max_digits=6)),
                ('pre_pay_discount', models.DecimalField(decimal_places=2, default='0.0', max_digits=6)),
                ('multiple_purchase_discount', models.DecimalField(decimal_places=2, default='0.0', max_digits=6)),
                ('credit_applied', models.DecimalField(decimal_places=2, default='0.0', max_digits=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_type', models.CharField(choices=[('Subject', 'Subject'), ('ClassOffer', 'ClassOffer'), ('Other', 'Other')], default='Subject', editable=False, max_length=15)),
                ('content_type', models.CharField(choices=[('url', 'External Link'), ('file', 'Formatted Text File'), ('text', 'Plain Text'), ('video', 'Video file on our site'), ('image', 'Image file on our site'), ('link', 'Webpage on our site'), ('email', 'Email file')], max_length=15)),
                ('user_type', models.PositiveSmallIntegerField(choices=[(0, 'Public'), (1, 'Student'), (2, 'Teacher'), (3, 'Admin')], default=1, help_text='Who is this for?')),
                ('avail', models.PositiveSmallIntegerField(choices=[(0, 'On Sign-up, before week 1)'), (1, 'After week 1'), (2, 'After week 2'), (3, 'After week 3'), (4, 'After week 4'), (5, 'After week 5'), (200, 'After completion')], default=0, help_text='When is this resource available?')),
                ('expire', models.PositiveSmallIntegerField(default=0, help_text='Number of published weeks? (0 for always)')),
                ('imagepath', models.ImageField(blank=True, help_text='If an image, upload here', upload_to='resource/')),
                ('filepath', models.FileField(blank=True, help_text='If a file, upload here', upload_to='resource/')),
                ('link', models.URLField(blank=True, help_text='External or Internal links go here', max_length=191)),
                ('text', models.TextField(blank=True, help_text='Text chunk used in page or email publication')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('key_day_date', models.DateField(default=classwork.models.default_key_day, verbose_name='main class start date')),
                ('max_day_shift', models.SmallIntegerField(default=-2, help_text='Use negative numbers if others are before the main class day.', verbose_name='number of days other classes are away from main class')),
                ('num_weeks', models.PositiveSmallIntegerField(default=5, verbose_name='number of class weeks')),
                ('skip_weeks', models.PositiveSmallIntegerField(default=0, verbose_name='skipped mid-session class weeks')),
                ('flip_last_day', models.BooleanField(default=False, help_text='Possibly true if the skipped class is not on the day that normally is the end of the session.', verbose_name='due to skipped weeks, does the session ending switch between a non-key vs key day?')),
                ('break_weeks', models.PositiveSmallIntegerField(default=0, verbose_name='break weeks after this session')),
                ('publish_date', models.DateField(blank=True, default=classwork.models.default_publish)),
                ('expire_date', models.DateField(blank=True, help_text='If blank, this will be computed')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name used to find this content', max_length=120)),
                ('text', models.TextField(blank=True, help_text='Text chunk used in page or email publication')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
