# Generated by Django 3.0.7 on 2020-06-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
