# Generated by Django 2.2.1 on 2019-09-02 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name used to find this content', max_length=120)),
                ('text', models.TextField(blank=True, help_text='Text chunk used in page or email publication')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='classwork.Profile'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='classoffer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classwork.ClassOffer'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classwork.Payment'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classwork.Profile'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='filepath',
            field=models.FileField(blank=True, help_text='If a file, upload here', upload_to='resource/'),
        ),
    ]
