# Generated by Django 2.1.3 on 2019-01-30 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190129_1959'),
        ('classwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('level', models.IntegerField(default=0, verbose_name='skill level')),
                ('credit', models.FloatField(default=0, verbose_name='Class Payment Credit')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classoffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classwork.ClassOffer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classwork.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='taken',
            field=models.ManyToManyField(related_name='students', through='classwork.Registration', to='classwork.ClassOffer'),
        ),
    ]
