# Generated by Django 2.1.3 on 2019-01-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classoffer',
            name='num_level',
            field=models.IntegerField(default=0),
        ),
    ]
