# Generated by Django 2.1.3 on 2019-01-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0002_classoffer_num_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classoffer',
            name='num_level',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
