# Generated by Django 3.0.7 on 2020-06-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0002_auto_20200624_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expire_date',
            field=models.DateField(blank=True),
        ),
    ]
