# Generated by Django 3.0.8 on 2020-07-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0002_auto_20200724_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='taught',
        ),
        migrations.AddField(
            model_name='classoffer',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to={'user__is_active': True}, related_name='taught', to='classwork.Staff'),
        ),
    ]
