# Generated by Django 2.2.8 on 2020-01-24 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0002_auto_20190902_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='classoffer',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classwork.Location'),
        ),
        migrations.AddField(
            model_name='subject',
            name='full_price',
            field=models.DecimalField(decimal_places=2, default='70.0', max_digits=9),
        ),
        migrations.AddField(
            model_name='subject',
            name='multiple_purchase_discount',
            field=models.DecimalField(decimal_places=2, default='10.0', max_digits=9),
        ),
        migrations.AddField(
            model_name='subject',
            name='pre_pay_discount',
            field=models.DecimalField(decimal_places=2, default='5.0', max_digits=9),
        ),
        migrations.AddField(
            model_name='subject',
            name='qualifies_as_multi_class_discount',
            field=models.BooleanField(default=True),
        ),
    ]
