# Generated by Django 3.0.8 on 2020-08-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0003_auto_20200725_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='classoffer',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='related_type',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='subject',
        ),
        migrations.AddField(
            model_name='resource',
            name='classoffers',
            field=models.ManyToManyField(blank=True, related_name='resources', to='classwork.ClassOffer'),
        ),
        migrations.AddField(
            model_name='resource',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='resources', to='classwork.Subject'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='avail',
            field=models.PositiveSmallIntegerField(choices=[(0, 'On Sign-up, before week 1)'), (1, 'After class 1'), (2, 'After class 2'), (3, 'After class 3'), (4, 'After class 4'), (5, 'After class 5'), (6, 'After class 6'), (200, 'After completion')], default=0, help_text='When is this resource available?'),
        ),
    ]
