# Generated by Django 3.0.7 on 2020-06-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0003_auto_20200626_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='break_weeks',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Break weeks after this session'),
        ),
        migrations.AddField(
            model_name='session',
            name='flip_last_day',
            field=models.BooleanField(default=False, help_text='This is probably only true if the skipped class is not on the weekday that normally is the end of the session.', verbose_name='Due to skipped weeks, does the session ending switch between a non-key vs key day?'),
        ),
        migrations.AddField(
            model_name='session',
            name='skip_weeks',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='How many class weeks are skipped mid-session?'),
        ),
        migrations.AlterField(
            model_name='session',
            name='expire_date',
            field=models.DateField(blank=True, help_text='If blank, this will be computed'),
        ),
        migrations.AlterField(
            model_name='session',
            name='max_day_shift',
            field=models.SmallIntegerField(default=0, help_text='Use negative numbers if others are before the main class day.', verbose_name='Number of days other classes are away from Main Class'),
        ),
        migrations.AlterField(
            model_name='session',
            name='num_weeks',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Number of Class Weeks'),
        ),
    ]
