# Generated by Django 3.0.8 on 2020-08-27 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classwork', '0004_auto_20200810_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'staff'},
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='resource',
            name='avail',
            field=models.PositiveSmallIntegerField(choices=[(0, 'On Sign-up, before starting'), (1, 'After class 1'), (2, 'After class 2'), (3, 'After class 3'), (4, 'After class 4'), (5, 'After class 5'), (6, 'After class 6'), (200, 'After completion')], default=0, help_text='When is this resource available?'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, help_text='Only used as staff notes', verbose_name='Staff Notes Description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='text',
            field=models.TextField(blank=True, help_text='Content used in page or email publication', verbose_name='Text Content'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='text',
            field=models.TextField(blank=True, help_text='Text content used in page or email publication'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='listing',
            field=models.SmallIntegerField(blank=True, default=10, help_text='Negative numbers will not be shown. '),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
