# Generated by Django 3.0.8 on 2020-07-11 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0005_auto_20200710_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='related_type',
            field=models.CharField(choices=[('Subject', 'Subject'), ('ClassOffer', 'ClassOffer'), ('Other', 'Other')], default='Subject', editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='resource',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classwork.Subject'),
        ),
    ]
