# Generated by Django 3.0.8 on 2020-07-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0007_auto_20200713_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='level_num',
            field=models.DecimalField(decimal_places=1, default=3.5, help_text='Will be computed if left blank. ', max_digits=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='credit_applied',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=6),
        ),
        migrations.AlterField(
            model_name='payment',
            name='full_price',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=6),
        ),
        migrations.AlterField(
            model_name='payment',
            name='multiple_purchase_discount',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=6),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pre_pay_discount',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=1530),
        ),
        migrations.AlterField(
            model_name='subject',
            name='full_price',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='subject',
            name='multiple_purchase_discount',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='subject',
            name='pre_pay_discount',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
    ]
