# Generated by Django 2.1.7 on 2019-03-11 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0008_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='vid_wk1',
            field=models.ForeignKey(blank=True, limit_choices_to={'content_type': 'video'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subect_vid1', to='classwork.Resource'),
        ),
        migrations.AddField(
            model_name='subject',
            name='vid_wk2',
            field=models.ForeignKey(blank=True, limit_choices_to={'content_type': 'video'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subect_vid2', to='classwork.Resource'),
        ),
        migrations.AddField(
            model_name='subject',
            name='vid_wk3',
            field=models.ForeignKey(blank=True, limit_choices_to={'content_type': 'video'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subect_vid3', to='classwork.Resource'),
        ),
        migrations.AddField(
            model_name='subject',
            name='vid_wk4',
            field=models.ForeignKey(blank=True, limit_choices_to={'content_type': 'video'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subect_vid4', to='classwork.Resource'),
        ),
        migrations.AddField(
            model_name='subject',
            name='vid_wk5',
            field=models.ForeignKey(blank=True, limit_choices_to={'content_type': 'video'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subect_vid5', to='classwork.Resource'),
        ),
    ]
