# Generated by Django 3.0.8 on 2020-07-25 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200724_2235'),
        ('classwork', '0008_auto_20200717_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classoffer',
            name='teachers',
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classwork.Payment'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='level_num',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Will be computed if left blank. ', max_digits=3),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, max_length=760)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('level', models.IntegerField(blank=True, default=0, verbose_name='skill level')),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('taken', models.ManyToManyField(related_name='students', through='classwork.Registration', to='classwork.ClassOffer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, max_length=760)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('listing', models.SmallIntegerField(blank=True, help_text='listing order')),
                ('tax_doc', models.CharField(blank=True, max_length=9)),
                ('taught', models.ManyToManyField(related_name='teachers', to='classwork.ClassOffer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_for', to='classwork.Student'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='classwork.Student'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classwork.Student'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
