# Generated by Django 2.1.7 on 2019-03-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0010_auto_20190310_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='email_1',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='email_2',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='email_3',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='email_4',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='email_5',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='email_wk1',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='email_wk2',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='email_wk3',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='email_wk4',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='email_wk5',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='syllabus',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher_plan',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='vid_wk1',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='vid_wk2',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='vid_wk3',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='vid_wk4',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='vid_wk5',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='video_wk1',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='video_wk2',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='video_wk3',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='video_wk4',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='video_wk5',
        ),
    ]
