# Generated by Django 2.1.5 on 2019-02-19 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='credit_applied',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=9),
        ),
        migrations.AddField(
            model_name='payment',
            name='full_price',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=9),
        ),
        migrations.AddField(
            model_name='payment',
            name='multiple_purchase_discount',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=9),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_for_other', to='classwork.Profile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='pre_pay_discount',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=9),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='classwork.Profile'),
        ),
    ]
