# Generated by Django 2.1.5 on 2019-02-20 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0005_auto_20190219_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classwork.Payment'),
        ),
    ]
