# Generated by Django 2.1.5 on 2019-03-04 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0006_auto_20190219_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classoffer',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classwork.Session'),
        ),
        migrations.AlterField(
            model_name='classoffer',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classwork.Subject'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='classoffer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classwork.ClassOffer'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classwork.Profile'),
        ),
    ]
