# Generated by Django 2.1.7 on 2019-03-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0011_auto_20190311_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='filepath',
            field=models.FileField(help_text='If a file, upload here', null=True, upload_to='resource/'),
        ),
    ]
