# Generated by Django 2.1.7 on 2019-03-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0012_auto_20190318_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='expire',
            field=models.PositiveSmallIntegerField(default=0, help_text='It expires how many weeks after being published? (0 for never)'),
        ),
        migrations.AddField(
            model_name='resource',
            name='imagepath',
            field=models.ImageField(help_text='If an image, upload here', null=True, upload_to='resource/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='link',
            field=models.CharField(help_text='External or Internal links go here', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='text',
            field=models.TextField(blank=True, help_text='Text chunk used in page or email publication', null=True),
        ),
    ]
