# Generated by Django 2.1.7 on 2019-03-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0013_auto_20190318_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
