# Generated by Django 2.1.7 on 2019-03-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0014_resource_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
