# Generated by Django 2.1.7 on 2019-04-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0017_auto_20190318_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='expire',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of weeks it stays published? (0 for always)'),
        ),
    ]
