# Generated by Django 2.2.1 on 2019-09-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhc',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='userhc',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
