# Generated by Django 2.2.8 on 2020-01-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200126_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhc',
            name='billing_country_area',
            field=models.CharField(blank=True, default='WA', max_length=2),
        ),
    ]
